# Generated by Django 3.1 on 2020-08-24 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0002_auto_20200817_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact2',
        ),
        migrations.AddField(
            model_name='project',
            name='contact1_email',
            field=models.EmailField(default='default@default.com', max_length=254, verbose_name='primary contact email'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact1_name',
            field=models.CharField(default='default', max_length=150, verbose_name='primary contact name'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact1_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='\\+?\\d{9,15}')], verbose_name='primary phone number'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='secondary contact email'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='seconday contact name'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='\\+?\\d{9,15}')], verbose_name='secondary phone number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image displayed on page'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
