# Generated by Django 3.1 on 2020-08-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0003_auto_20200824_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact1_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='primary contact email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact1_name',
            field=models.CharField(max_length=150, null=True, verbose_name='primary contact name'),
        ),
    ]
