# Generated by Django 3.1 on 2020-08-24 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0004_auto_20200824_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='project approved'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact1_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='\\+?\\d{9,15}')], verbose_name='primary phone number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='\\+?\\d{9,15}')], verbose_name='secondary phone number'),
        ),
    ]
