# Generated by Django 3.1 on 2020-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0005_auto_20200824_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='image displayed on page'),
        ),
    ]
