# Generated by Django 3.1 on 2020-08-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0006_auto_20200828_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image displayed on page'),
        ),
    ]
