# Generated by Django 3.1 on 2020-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0007_auto_20200829_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image displayed on page'),
        ),
    ]
