# Generated by Django 3.1 on 2020-09-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0008_auto_20200830_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='thumbnail displayed on page'),
        ),
    ]
