# Generated by Django 3.1 on 2020-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0009_project_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image displayed on page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='thumbnail displayed on page'),
        ),
    ]
