# Generated by Django 3.1 on 2020-09-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0010_auto_20200907_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.AddField(
            model_name='project',
            name='contact1_url',
            field=models.URLField(null=True, verbose_name='research repository URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact2_url',
            field=models.URLField(null=True, verbose_name='research repository URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.CharField(max_length=300, null=True, verbose_name='project short description ~30 words'),
        ),
    ]
