# Generated by Django 3.1 on 2020-09-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0011_auto_20200917_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='project',
            name='contact2_url',
            field=models.URLField(blank=True, null=True, verbose_name='research repository URL'),
        ),
    ]
