# Generated by Django 3.1 on 2020-10-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0013_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact1_url',
            field=models.URLField(null=True, verbose_name='<a href="https://research-repository.uwa.edu.au/" target="_blank">Research Repositry URL<a/>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact2_url',
            field=models.URLField(blank=True, null=True, verbose_name='<a href="https://research-repository.uwa.edu.au/" target="_blank">Research Repositry URL<a/>'),
        ),
    ]
