# Generated by Django 3.1 on 2020-10-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0014_auto_20201004_1639'),
        ('hmsSite', '0014_auto_20201002_1050'),
    ]

    operations = [
    ]
