# Generated by Django 3.1 on 2020-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0015_merge_20201005_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact2_url',
            field=models.URLField(blank=True, null=True, verbose_name='<div class= "url2"> <a href="https://research-repository.uwa.edu.au/" target="_blank">Research Repositry URL<a/></div>'),
        ),
    ]
