# Generated by Django 3.1 on 2020-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0018_auto_20201011_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_stock',
            options={'verbose_name': 'Stock Image', 'verbose_name_plural': 'Stock Images'},
        ),
        migrations.AlterField(
            model_name='image_stock',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='image_stock_name'),
        ),
    ]
