# Generated by Django 3.1 on 2020-10-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0019_auto_20201011_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_stock',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/', verbose_name='stock image thumbnail'),
        ),
        migrations.AlterField(
            model_name='image_stock',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='stock_image_no_upload'),
        ),
    ]
