# Generated by Django 3.1 on 2020-10-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0020_auto_20201011_1839'),
        ('hmsSite', '0018_auto_20201012_2047'),
    ]

    operations = [
    ]
