# Generated by Django 3.1 on 2020-10-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsSite', '0021_merge_20201014_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_stock',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='stock image thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact1_url',
            field=models.URLField(null=True, verbose_name='research repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact2_url',
            field=models.URLField(blank=True, null=True, verbose_name='research repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='is the project still relevant and ongoing'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsSite.image_stock'),
        ),
    ]
